version: '3.3'
volumes:
  postgres_data:
services:
  db:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
