# Generated by Django 3.2.7 on 2021-09-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210904_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='chat.board'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship', to='chat.board'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='location',
            field=models.ManyToManyField(related_name='ship', to='chat.Location'),
        ),
    ]
